# Site Title
title: Kee Projects

# Embed metadata (i.e. Discord, Twitter)
description: Play, Create, Share. Kee Projects is comprised of handcrafted creations, publicly shared with everyone.

# Root for content downloads (local mode = /assets/content)
cdnroot: /assets/content/

# Site-wide navigation (or per-page: page.links => site.navitems.primary)
navitems:
  primary:
    - url: '../'
      icon: ''
  secondary:
    - url: '//github.com/Kee7702/staging.kee7702.tk'
      icon: '<img style="height:24px" src="/assets/github.svg">'

plugins:
  - jekyll-default-layout
  - jekyll-redirect-from