# Site Title
title: Kee Projects
name: Projects by Kee7702

# Embed metadata (i.e. Discord, Twitter)
description: "Catch up on the latest from me or simply take a look at some of what I've made over the years."
theme_color: '#2e2e37'

# Root for content downloads
cdnroot: /assets/content/

# Site-wide navigation (or per-page: page.links => site.navitems.primary)
navitems:
#  primary:
#    - url: '../'
#      icon: ''
  secondary:
    - url: '//github.com/Kee7702/Kee7702.github.io'
      icon: '<img style="height:24px" src="/assets/github.svg">'

redirect_from:
  json: false

plugins:
  - jekyll-default-layout
  - jekyll-redirect-from
